- name: "Install essential packages using apt"
  apt:
    name: ["build-essential", "git", "tmux", "tmuxinator", "htop", "valgrind",
           "curl", "ssh", "cmake", "python3-dev"]
    state: present
  become: yes
  when: ansible_facts["pkg_mgr"] == "apt"

- name: "Install essential packages using brew"
  community.general.homebrew:
    name: ["git", "tmux", "tmuxinator", "htop", "curl", "cmake"]
    state: present
  when: ansible_facts["pkg_mgr"] == "homebrew"

- name: "Check if ssh keys exist"
  stat:
      path: ~/.ssh/id_rsa
  register: stat_result

- name: "Generate ssh keys"
  openssh_keypair:
      path: ~/.ssh/id_rsa
  when: not stat_result.stat.exists

- name: "Install dlang"
  include_tasks: dlang.yml

- name: "Install the editors"
  include_tasks: ide.yml
