- name: "Create dlang path"
  file:
      path: ~/dlang
      state: directory

- name: "Download dlang.org/install.sh"
  get_url:
      url: "https://dlang.org/install.sh"
      dest: ~/dlang/install.sh
      mode: 0775
  register: r_dlang

- name: "Install gdc"
  shell:
      cmd: ~/dlang/install.sh install gdc
      executable: /bin/bash
  when: r_dlang.changed != false

